### ISSUE TITLE
step counter needs to be a long, not an int: 

### ISSUE THREAD

**Issue by mark-fathom** [fathominfo/delphy-web#20]
<img width="350" alt="Screen Shot 2024-10-31 at 12 01 23 PM" src="https://github.com/user-attachments/assets/30ae54c1-3a0e-4686-8e51-24eed3b7e349">

**Comment by mark-fathom** [comment]
Looking at some [emscripten documentation](https://emscripten.org/docs/tools_reference/settings_reference.html?highlight=main), maybe we want to try `MEMORY64=1`?
```
MEMORY64
The “architecture” to compile for. 0 means the default wasm32, 1 is the full end-to-end wasm64 mode, and 2 is wasm64 for clang/lld but lowered to wasm32 in Binaryen (such that it can run on wasm32 engines, while internally using i64 pointers). Assumes WASM_BIGINT.
```

Other pertinent options might be `WASM_BIGINT` and `ERROR_ON_WASM_CHANGES_AFTER_LINK`.

**Comment by patvarilly** [comment]
Ahhh!!  Foiled by WebAssembly again.  Compiling with `-sWASM_BIGINT` solves the issue.  A good explanation of the problem is [here](https://v8.dev/features/wasm-bigint).  Basically, since WebAssembly doesn't want to automatically destroy 64-bit ints by putting them into doubles, the default way of handling int64's is crazy (it splits them into 32-bit high and low words, and the high word is returned out of band!).  Since JS now has BigInts almost everywhere, WASM can use that instead, but you need to enable a flag (`WASM_BIGINT`) to do so.  Long story short: a quick recompile with that flag (coming) should fix the problem, and the only quirk is that the `stepsHists` array (and any other place where 64-bit quantities were supposed to show up) will be JS BigInts.

**Comment by mark-fathom** [comment]
Thank you!
